version: '3'

services:
  mlist-backend:
    command: ['/app/config.yaml']
    image: olegdayo/mlist-backend
    ports:
      - '8080:8080'
      - '2112:2112'
    volumes:
      - './configs/backend.yaml:/app/config.yaml:ro'
    depends_on:
      db:
        condition: service_healthy
