version: '3'

services:
  # otel-collector:
  #   image: otel/opentelemetry-collector-contrib
  #   hostname: otel-collector
  #   volumes:
  #     - ./configs/otel-collector.yaml:/etc/otelcol-contrib/config.yaml
  #   ports:
  #     - '4317:4317'

  loki:
    image: grafana/loki:latest
    command: -config.file=/etc/loki/loki.yaml
    volumes:
      - ./configs/loki.yaml:/etc/loki/loki.yaml

  # jaeger:
  #   image: jaegertracing/all-in-one
  #   hostname: jaeger
  #   environment:
  #     - COLLECTOR_OTLP_ENABLED=true
  #   ports:
  #     - '16686:16686'

  # db-exporter:
  #   image: prometheuscommunity/postgres-exporter
  #   hostname: pg-db-exporter
  #   environment:
  #     DATA_SOURCE_NAME: "postgres://user:password@auth-db:5432/db?sslmode=disable"
  #   depends_on:
  #     core-db:
  #       condition: service_healthy

  prometheus:
    image: prom/prometheus
    hostname: prometheus
    ports:
      - '9090:9090'
    volumes:
      - ./configs/prometheus.yaml:/etc/prometheus/prometheus.yml
    depends_on:
      - db-exporter

  grafana:
    image: grafana/grafana
    hostname: grafana
    ports:
      - '3000:3000'
    environment:
      - GF_SECURITY_ADMIN_USER=telescope
      - GF_SECURITY_ADMIN_PASSWORD=telescope
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_ANONYMOUS_ORG_Name=telescope
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Viewer
    volumes:
      - grafana-data:/var/lib/grafana
    depends_on:
      - prometheus

volumes:
  grafana-data:
