[SERVICE]
    Flush         1
    Log_Level     info

[INPUT]
    Name          forward
    Listen        0.0.0.0
    Port          24224
    Tag           mlist.*

[OUTPUT]
    Name          loki
    Match         *
    Host          loki
    Port          3100
    # Line_Format   regex
    # Log_Key       log
    Labels        job=fluent-bit, container_name=${HOSTNAME}
    label_keys    $container_name, $source
