apiVersion: apps/v1
kind: Deployment
metadata:
  name: bad-model-image-version-not-in-list
  labels:
    app: bad-model-image-version-not-in-list
spec:
  ...
  template:
  ...
    spec:
      initContainers:
        - name: weights-downloader
        ...
        - name: weights-verifier
        ...
      containers:
        - name: bad-model-image-version-not-in-list
          image: olegdayo/example-service:v2.0.0
          ports:
            - containerPort: 8000
          resources:
          ...
      volumes:
      ...
