apiVersion: apps/v1
kind: Deployment
metadata:
  name: good-model-small
  labels:
    app: good-model-small
spec:
  ...
    spec:
      initContainers:
        - name: weights-downloader
          image: amazon/aws-cli:2.34.44
          ...
        - name: weights-verifier
          image: ghcr.io/sigstore/cosign/cosign:v2.6.2
          ...
      containers:
        - name: good-model-small
          image: olegdayo/example-service:v2.0.0
          ...
