apiVersion: apps/v1
kind: Deployment
metadata:
  name: bad-model-unsigned-weights
  labels:
    app: bad-model-unsigned-weights
spec:
  replicas: 3
  selector:
    matchLabels:
      app: bad-model-unsigned-weights
  template:
    metadata:
      labels:
        app: bad-model-unsigned-weights
    spec:
      containers:
        - name: bad-model-unsigned-weights
          image: olegdayo/example-service:v2.0.2 # TODO
          ports:
            - containerPort: 8000
          resources:
            requests:
              cpu: 1
              memory: 256Mi
            limits:
              cpu: 4
              memory: 4Gi
      volumes:
        - name: weights
          emptyDir: {}
