apiVersion: apps/v1
kind: Deployment
metadata:
  name: bad-model-image-no-init-containers
  labels:
    app: bad-model-image-no-init-containers
spec:
  replicas: 3
  selector:
    matchLabels:
      app: bad-model-image-no-init-containers
  template:
    metadata:
      labels:
        app: bad-model-image-no-init-containers
    spec:
      containers:
        - name: bad-model-image-no-init-containers
          image: olegdayo/example-service:v2.0.0
          ports:
            - containerPort: 8000
          resources:
            requests:
              cpu: 1
              memory: 256Mi
            limits:
              cpu: 4
              memory: 4Gi
