version: '3'

services:
  loki:
    image: grafana/loki:latest
    command: -config.file=/etc/loki/loki.yaml
    volumes:
      - ./configs/loki.yaml:/etc/loki/loki.yaml

  fluent-bit:
    image: fluent/fluent-bit:3.0
    volumes:
      - ./configs/fluent-bit.conf:/fluent-bit/etc/fluent-bit.conf
    ports:
      - "24224:24224"   # Receive logs from containers
      - "2020:2020"     # Monitoring endpoint
    depends_on:
      - loki

  # jaeger:
  #   image: jaegertracing/all-in-one
  #   hostname: jaeger
  #   environment:
  #     - COLLECTOR_OTLP_ENABLED=true
  #   ports:
  #     - '16686:16686'

  db-exporter:
    image: prometheuscommunity/postgres-exporter
    hostname: pg-db-exporter
    environment:
      DATA_SOURCE_NAME: "postgres://user:password@db:5432/db?sslmode=disable"
    depends_on:
      db:
        condition: service_healthy

  prometheus:
    image: prom/prometheus
    hostname: prometheus
    ports:
      - '9090:9090'
    volumes:
      - ./configs/prometheus.yaml:/etc/prometheus/prometheus.yml
    depends_on:
      - db-exporter

  grafana:
    image: grafana/grafana
    hostname: grafana
    ports:
      - '3000:3000'
    environment:
      - GF_SECURITY_ADMIN_USER=mlist
      - GF_SECURITY_ADMIN_PASSWORD=mlist
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_ANONYMOUS_ORG_Name=mlist
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Viewer
    volumes:
      - grafana-data:/var/lib/grafana
    depends_on:
      - prometheus

volumes:
  grafana-data:
