version: '3'

services:
  ceph-s3:
    image: quay.io/ceph/demo:latest-reef
    container_name: ceph-s3
    privileged: true
    environment:
      NETWORK_AUTO_DETECT: "1"
      CEPH_DEMO_UID: "1"
      CEPH_DEMO_ACCESS_KEY: "something-you-shant-know"
      CEPH_DEMO_SECRET_KEY: "something-you-shant-see"
      RGW_NAME: "localhost"
      CEPH_PUBLIC_NETWORK: "0.0.0.0/0"
      MON_IP: "127.0.0.1"
    command: demo
    ports:
      - "7480:8080"
    volumes:
      - ceph-data:/var/lib/ceph

volumes:
  ceph-data:
