apiVersion: apps/v1
kind: Deployment
metadata:
  name: bad-model
  labels:
    app: bad-model
spec:
  replicas: 3
  selector:
    matchLabels:
      app: bad-model
  template:
    metadata:
      labels:
        app: bad-model
    spec:
      containers:
        - name: bad-model
          image: docker.io/olegdayo/example-service:v0.0.6
          ports:
            - containerPort: 8000
