apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: deploy-verifier
spec:
  validationFailureAction: Enforce
  background: false
  rules:
    - name: block-manual-deploys
      match:
        any:
          - resources:
              kinds:
                - Deployment
      validate:
        message: "Manual deploys are blocked, either run a CI/CD pipeline or use GitOps!"
        deny:
          conditions:
            all:
              - key: "{{ request.operation }}"
                operator: AnyIn
                value:
                  - CREATE
                  - UPDATE
                  - DELETE
              - key: "{{ request.userInfo.username }}"
                operator: AnyNotIn
                value:
                  # GitOps controller
                  - 'system:serviceaccount:argocd:argocd-application-controller'
                  # CI/CD deployer service accounts
                  - 'system:serviceaccount:default:deployer'
