apiVersion: apps/v1
kind: Deployment
metadata:
  name: good-model
  labels:
    app: good-model
spec:
  replicas: 3
  selector:
    matchLabels:
      app: good-model
  template:
    metadata:
      labels:
        app: good-model
    spec:
      initContainers:
        - name: weights-downloader
        - name: weights-verifier
      containers:
        - name: good-model
          image: olegdayo/example-service:v0.0.8
          ports:
            - containerPort: 8000
  volumes:
    - name: weights
      emptyDir: {}
