apiVersion: policies.kyverno.io/v1
kind: ImageValidatingPolicy
metadata:
  name: image-verifier
spec:
  webhookConfiguration:
    timeoutSeconds: 30
  evaluation:
   background:
    enabled: true
  validationActions: [Deny]
  matchConstraints:
    resourceRules:
      - apiGroups: [""]
        apiVersions: ["v1"]
        operations: ["CREATE", "UPDATE"]
        resources: ["pods"]
  matchImageReferences:
        - glob : "docker.io/olegdayo/example-service:*"
        - glob : "olegdayo/example-service:*"
  attestors:
  # - name: cosign
  #   cosign:
  #    key:
  #     data: |
  #       -----BEGIN PUBLIC KEY-----
  #       MFkwEwYHKoZIzj0CAQYIKoZIzj0DAQcDQgAEF4i6vQWkl2v+UYdP/YWbOn+j8myt
  #       W7EembEFWIlXFkuRrVOnEFw29HsxPdarMp3EJx5PCOGpbVeABcqsLuuF4w==
  #       -----END PUBLIC KEY-----
    - name: cosign
      cosign:
        key:
          kms: hashivault://signer
  validations:
    - message: image is not authorized
      expression: |
       images.containers.map(image,
         verifyImageSignatures(image, [attestors.cosign])).all(e, e > 0)
