apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: mlist-validation
spec:
  validationFailureAction: Enforce
  background: false
  rules:
    - name: check-image-repo-tag
      match:
        any:
          - resources:
              kinds:
                - Pod
              operations:
                - CREATE
      context:
        - name: imageData
          variable:
            jmesPath: "request.object.spec.containers[].image"

        - name: apiResponse
          apiCall:
            service:
              url: 'http://64.225.73.53/api/models/lookup?repository={{ (images.containers.*.registry)[0] }}/{{ (images.containers.*.path)[0] }}&version={{ (images.containers.*.tag)[0] }}'
              # jmesPath: '{error: error}'
              # default:
              #   error: "request_failed"
            method: GET

      validate:
        message: "Image is not found in MList"
        deny:
          conditions:
            any:
              - key: "{{ apiResponse.error }}"
                operator: NotEquals
                value: 'null'
