apiVersion: v1
kind: Secret
metadata:
  name: init-container-s3-creds
  namespace: models
type: Opaque
stringData:
  access_key: smth
  secret_access_key: smth
---
apiVersion: v1
kind: Secret
metadata:
  name: init-container-vault-creds
  namespace: models
type: Opaque
stringData:
  address: http://127.0.0.1:8200
  token: s.smth
---
apiVersion: v1
kind: Secret
metadata:
  name: kyverno-vault-creds
  namespace: kyverno
type: Opaque
stringData:
  address: http://127.0.0.1:8200
  token: s.smth
---
apiVersion: v1
kind: Secret
metadata:
  name: kyverno-mlist-creds
  namespace: kyverno
type: Opaque
stringData:
  address: http://127.0.0.1:8200
