apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: verify-image-signature
spec:
  validationFailureAction: Enforce
  webhookTimeoutSeconds: 30
  failurePolicy: Fail
  background: false
  rules:
    - name: check-signature
      match:
        any:
          - resources:
              kinds:
                - Pod
      verifyImages:
        - imageReferences:
            - "docker.io/olegdayo/example-service:v*" # Scope of images to check
          attestors:
            - entries:
                - keys:
                    kms: hashivault://signer
                    rekor:
                      ignoreTlog: true
                      url: https://rekor.sigstore.dev
