name: Deploy

on:
  workflow_dispatch:
    inputs:
      model:
        description: "Model to deploy"
        required: true
        type: choice
        default: good-model-nano
        options:
          - bad-model-image-repo-not-in-list
          - bad-model-image-version-not-in-list
          - bad-model-malicious-downloader-init-container-env
          - bad-model-malicious-verifier-init-container-command
          - bad-model-malicious-verifier-init-container-image
          - bad-model-image-no-init-containers
          - bad-model-image-no-verifier-init-container
          - bad-model-unsigned-image
          - bad-model-fake-weights
          - good-model-nano
          - good-model-small

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Check Out
        uses: actions/checkout@v4

      - name: Install kubectl
        uses: azure/setup-kubectl@v4

      - name: Configure kube access
        run: |
          echo "${{ secrets.K8S_CA_CERT }}" | base64 -d > ca.crt

          kubectl config set-cluster mlops-cluster \
            --server="${{ secrets.K8S_URL }}" \
            --certificate-authority=ca.crt

          kubectl config set-credentials deployer \
            --token="${{ secrets.K8S_TOKEN }}"

          kubectl config set-context mlops \
            --cluster=mlops-cluster \
            --user=deployer \

          kubectl config use-context mlops

      - name: Deploy model
        run: kubectl apply -f ./k8s/models/${{ inputs.model }}.yaml -n models
